# These are supported funding model platforms

github: christianhelle
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: christianhelle
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: christianhelle
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ["https://paypal.me/christianhelle", "https://buymeacoffee.com/christianhelle"]
