name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - "!.github/workflows/build.yml"
      - "!Cargo.toml"
      - "!Cargo.lock"
      - "!src/**/*.rs"
    branches:
      - "*"
  pull_request:
    paths-ignore:
      - "**/*"
      - "!.github/workflows/build.yml"
      - "!Cargo.toml"
      - "!Cargo.lock"
      - "!src/**/*.rs"
    branches:
      - "*"

jobs:
  build:
    name: 👌 Verify build
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v6
      - name: 🦀 Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: 📦 Cache Cargo
        uses: Swatinem/rust-cache@v3
      - name: 🛠️ Build
        run: cargo build --release --locked
      - name: 🧪 Test
        run: cargo test --locked
      - name: 🗳️ Upload
        uses: actions/upload-artifact@v7
        with:
          name: Binaries
          path: |
            target/release/httpgenerator
            README.md
