name: Codecov

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/codecov.yml'
      - '!legacy/**'
    branches:
      - '*'
  pull_request:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/codecov.yml'
      - '!legacy/**'
    branches:
      - '*'

env:
  VERSION: 1.0.0.${{ github.run_number }}
  CODECOV_TOKEN: 62284a15-ac3f-48bb-81c5-1204e3a8b66c

jobs:
  build:
    name: 👌 Verify build
    runs-on: windows-latest
    
    steps:
    
    - name: 🛒 Checkout repository
      uses: actions/checkout@v6

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'    
    
    - name: 🧪 Test
      run: dotnet test legacy/HttpGenerator.Tests/HttpGenerator.Tests.csproj -c Release --collect "XPlat Code coverage" -p:UseSourceLink=true -p:PackageVersion="${{ env.VERSION }}"
    
    - name: 🗳️ Upload
      uses: actions/upload-artifact@v7
      with:
        name: Packages
        path: |
          **/*.nupkg
          README.md

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: legacy
        files: '**/coverage.cobertura.xml'
        flags: unittests
        fail_ci_if_error: true
        verbose: true
