name: Codecov

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/codecov.yml'
      - '!Cargo.toml'
      - '!Cargo.lock'
      - '!src/**/*.rs'
    branches:
      - '*'
  pull_request:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/codecov.yml'
      - '!Cargo.toml'
      - '!Cargo.lock'
      - '!src/**/*.rs'
    branches:
      - '*'

jobs:
  build:
    name: 👌 Verify build
    runs-on: ubuntu-latest
    
    steps:
    
    - name: 🛒 Checkout repository
      uses: actions/checkout@v6

    - name: 🦀 Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: 📦 Cache Cargo
      uses: Swatinem/rust-cache@v3

    - name: 🧪 Generate coverage
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: 🧪 Test with coverage
      run: cargo llvm-cov --locked --lcov --output-path lcov.info

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v6
      with:
        files: lcov.info
        flags: unittests
        fail_ci_if_error: true
        verbose: true
