name: Release (Preview)

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/release-template.yml
    with:
      version: 0.5.0-preview.${{ github.run_number }}
    secrets: inherit