name: Release (Preview)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release-template.yml
    with:
      version: 1.1.0-preview.${{ github.run_number }}
    secrets: inherit
