name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "release"

jobs:
  publish:
    uses: ./.github/workflows/release-template.yml
    with:
      version: 1.0.1
    secrets: inherit
