name: Release (Preview)

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/release-template.yml
    with:
      version: 0.1.0.${{ github.run_number }}-preview
    secrets: inherit