name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "release"

permissions:
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/release-template.yml
    with:
      version: 1.1.0
      publish-crates: true
    secrets: inherit
