name: Smoke Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*"
      - '!src/**/*.cs'
      - '!src/**/*.csproj'
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
    branches:
      - "*"
  pull_request:
    paths-ignore:
      - "**/*"
      - '!src/**/*.cs'
      - '!src/**/*.csproj'
      - "!.github/workflows/template.yml"
      - "!.github/workflows/template-url.yml"
      - "!.github/workflows/smoke-tests.yml"
    branches:
      - "*"

jobs:
  
  file:
    strategy:
      matrix:        
        os: [ubuntu-latest]
    
    uses: ./.github/workflows/template.yml
    with:
      os: ${{ matrix.os }}
      command: 'dotnet run --project ../src/HttpGenerator/HttpGenerator.csproj'
  
  url:
    strategy:
      matrix:
        os: [ubuntu-latest]

    uses: ./.github/workflows/template-url.yml
    with:
      os: ${{ matrix.os }}
      command: 'dotnet run --project ../src/HttpGenerator/HttpGenerator.csproj'
