name: Run Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      production:
        required: false
        type: bool
        default: true

jobs:
  test:
    name: ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust
        if: ${{ !inputs.production }}
        uses: dtolnay/rust-toolchain@stable

      - name: Run smoke tests (production)
        if: ${{ inputs.production }}
        run: ./smoke-tests.ps1 -Production
        working-directory: test
        shell: pwsh

      - name: Run smoke tests (local build)
        if: ${{ !inputs.production }}
        run: ./smoke-tests.ps1
        working-directory: test
        shell: pwsh
